name: kouchuhyo_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  flutter_launcher_icons: ^0.13.1
  pdf: ^3.11.3
  printing: ^5.14.2
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  file_picker: ^10.2.0
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/koshita_base.jpg
    - assets/gawa_tsuma_base.jpg
    - assets/fonts/BIZUDPGothic-Regular.ttf
    - assets/fonts/BIZUDPGothic-Bold.ttf

  fonts:
   - family: BIZUDPGothic
     fonts:
       - asset: fonts/BIZUDPGothic-Regular.ttf
       - asset: fonts/BIZUDPGothic-Bold.ttf
         weight: 700
    
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

  windows:
    generate: true
    image_path: "assets/icon/app_icon.png" # アイコン画像のパス
    icon_size: 256 # アイコンの解像度
